# Generated by Django 5.2.6 on 2025-10-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(through='catalogs.ItemCategory', through_fields=('menuitem', 'category'), to='catalogs.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.option')),
            ],
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.ManyToManyField(through='catalogs.ItemOption', through_fields=('menuitem', 'option'), to='catalogs.option'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.restaurant'),
        ),
        migrations.CreateModel(
            name='Delivery_Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.restaurant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('menuitem', 'category'), name='unique_menuitem_category'),
        ),
        migrations.AddConstraint(
            model_name='itemoption',
            constraint=models.UniqueConstraint(fields=('menuitem', 'option'), name='unique_menuitem_option'),
        ),
    ]
